#!/usr/bin/env bash
#copies a file from your local machine to a host machine

if [ $# -lt 3 ];
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

local_file="$1"
host="$2"
username="$3"

if [ -z "$4" ];
then
    scp -o StrictHostKeyChecking=no "$local_file" "$username@$host":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$local_file" "$username@$host":~/
fi
