#!/usr/bin/env bash

if [ $# -lt 3 ];
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

local_file="$1"
host="$2"
username="$3"
remote_path="/home/ubuntu"

if [ -z "$4" ];
then
    scp -o StrictHostKeyChecking=no "$local_file" "$username@$host:$remote_path"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$local_file" "$username@$host:$remote_path"
fi
