#!/usr/bin/env bash
# sets up a new server to run nginx
sudo apt-get update
sudo apt-get install -y nginx


sudo ufw allow 'Nginx HTTP'


if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi


echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

#shellcheck disable=SC2154
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   root /var/www/html;
   index index.html;
   add_header X-Served-By \$hostname;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default

sudo mv -f default /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

